# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: article
  hint: false
  unique: true
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
  - name: picture
    type: EssencePicture
  - name: text
    type: EssenceRichtext
    default: :article_text
- name: essence
  hint: true
  unique: true
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
- name: video
  hint: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
  - name: file
    type: EssenceVideo
