# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html
- name: index
  taggable: true
  unique: false
  elements: [article]
  autogenerate: [article]
- name: test_layout
  taggable: true
  unique: false
  elements: [article]
  autogenerate: [article]
- name: bootstrap
  taggable: true
  unique: false
  elements: [article]
  autogenerate: [article]
- name: video_test
  taggable: true
  unique: false
  elements: [video]
  autogenerate: [video]
